services:
  - type: web
    name: person-detection-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 
      - key: PORT
        value: 8000
      - key: FRONTEND_URL
        value: https://final-project-inference.onrender.com/
      - key: MODEL_PATH
        value: util/yolo11n.pt
